ALTER TABLE incidents
    ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;